### ISSUE TITLE
Custom Trackers

### ISSUE THREAD

**Issue by sol1dus** [ember-insights/ember-insights#3]
- [x] Console adapter
- [x] Google Analytics adapter
- [x] Abstract to be extended for creation of your own adapter (for instance: Yandex Metrics)
- [ ] Yandex
- [ ] Elasticsearch adapter

**Comment by Zatvobor** [comment]
Some experiment around Yandex tracker is available, here https://github.com/ember-insights/ember-insights/compare/master...RuslanZavacky:rc-yandex-metrika

**Comment by Zatvobor** [comment]
segregated into independent issues
