### ISSUE TITLE
Clarify README 

### ISSUE THREAD

**Issue by Zatvobor** [ember-insights/ember-insights#50]
Add more about:
- [x] Change old project links within README, package.json, bower.json
- [x] Using a namespace such as `EmberInsights`
- [x] Move params description for `configure` and `track` function
- [x] Report any issues you have on our issue tracker
- [x] Clarify releasing steps/process
    - [x] Changelog and tagging convension

**Comment by RuslanZavacky** [comment]
@Zatvobor hey, do you have plan to clarify, how to use this addon? Can't find a way how to use it right :) Let's say, I want this addon to be injected to the route/controller/service/component, how to achieve that?

Thanks!

**Comment by Zatvobor** [comment]
Yeah, for sure. Can you please share with me what is unclear for you and what is your challenge (I mean, why do you need to inject something to component)?

BTW, you're able to try `ember server` (from `rc`). Let me know if you have further quetions.
