### ISSUE TITLE
Insights Configuration Proposal

### ISSUE THREAD

**Issue by RuslanZavacky** [ember-insights/ember-insights#88]
Hey,

I've tried to understand, why we even need initializer here, and I was not able to find a good answer for that.

First proposal, store configuration values in the application configuration. Configuration should be split by environment:

```javascript
var ENV= {
analyticsInsights: {
    development: {
      debug: true,
  
      insights: {
        ALL_TRANSITIONS: true,
        ALL_ACTIONS: false
      },
  
      trackers: {
        googleAnalytics: {
          setup: {
            webPropertyId: 'UA-2318996-47',
            linkid: true,
            displayFeatures: true
          },
  
          config: {
            trackTransitionsAs: 'pageview',
            fields: {
              version: ENV.APP.version
            }
          }
        }
      }
    }
  }
}
```

If you take a closer look, you can see some benefits from such configuration:

- [x] You specify environment, so no need to manually initiate tracking. 
- [x] You specify debug mode for each environment
- [x] You specify as many trackers as you want by its name

Based on this config, addon is able to start Insights tracker on its own, register it in the container and if anyone wants to use it in their components/routes/controllers etc, will create his own initializer to inject this dependency.

As we talked before, I'd like to use several trackers, first of them are going to be GA, Yandex.Metrics and Customer Metrics (they are gonna be saved into the local storage or just variable, and flushed to the server when XX metrics is gathered, later on stored in the ELK for insights)

As I don't want to create my own bicycle I want to focus my effort on something that is already in development and contirbute :)

I'd like to know what you guys think about or maybe some different ideas?

**Comment by Zatvobor** [comment]
Sure. I love to help you. Let's make a time for facilitated hangout. As a result, we'll produce a bunch of clear and useful issues.
